apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicdweb
  labels:
    app: nginx
    environment: staging
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: cicdweb
        name: cicdweb